name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm install
          npm run postinstall
          npm run build
          
      - name: Certificate
        env:
          AUTH: ${{ secrets.WINDOWS_CERTIFICATE }}
        run: |
          echo "$WINDOWS_CERTIFICATE" | base64 --decode > ${HOME}/windows.pfx    

      - name: Publish
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${HOME}/windows.pfx
          CSC_KEY_PASSWORD: ${{ secrets.CSC_WIN_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux

      - name: Clean
        run: |
          rm ${HOME}/windows.pfx